admin/fleetcommander/admin.py, tests/04_admin.py
companion branch is ready in the fc-client repository
=> admin: split applies-to into a different database/file

tests/01_logger_dconf.sh, tests/Makefile.am, tests/_01_wait_for_name.py
this makes the test run slightly faster and makes it more reliable
=> tests: use a python script to wait for bus name to appear instead of sleep

admin/fleetcommander/libvirtcontroller.py, admin/js/profiles.livesession.js, tests/01_logger_dconf.sh, tests/data/libvirt_domain-modified.xml
Changes for wip/dbuslaunch, wip/spicefices and wip/ci-fixed bundled in a single branch.
Tested and working but need to discuss if we add dbus-x11 as dependence because dbus-launch is included in that package
=> Bundled changes for wip/dbuslaunch, wip/spicefices and wip/ci-fixes branches

admin/Makefile.am, admin/cockpit/index.html, admin/cockpit/js/base.js, admin/cockpit/js/fcdbusclient.js, admin/cockpit/js/index.js, admin/fleetcommander/fcdbus.py, admin/fleetcommander/libvirtcontroller.py, admin/fleetcommander/sshcontroller.py, configure.ac, fleet-commander-admin.spec, tests/00_sshcontroller.py, tests/04_libvirt_controller.py, tests/Makefile.am, tests/_05_fcdbus_tests.py, tests/test_fcdbus_service.py, tests/tools/ssh-keygen, tests/tools/ssh-keyscan
Also removed python-crypto dependency because of separation of SSH related functions into a new module called sshcontroller
=> Changed libvirt connection method to pure SSH

admin/cockpit/js/index.js, admin/fleetcommander/sshcontroller.py, configure.ac, data/fleet-commander-dbus.service.in, fleet-commander-admin.spec
Also fixed missing dependency for python-gobject
Also fixed bug when trying to add a host to known hosts file if file directory not exists
Also fixed regression showing hypervisor configuration dialog if not already configured.
=> Fixed dbus service  autostart

.gitmodules, autogen.sh
- not possible to make, because the spice-html5 submodule is not initialized
- incorrect source for spice-html5
=> Fix issues after cloning the git repo

admin/cockpit/fleet-commander-admin/manifest.json
Fleet Commander is about managing all your machines, not about
tweaking a single one.
=> admin: Promote it to a Cockpit dashboard

admin/fleetcommander/fcdbus.py, logger/fleet_commander_logger.js, tests/00_freeipa.py, tests/_05_fcdbus_tests.py, tests/freeipamock.py
This pull request adds various fixes to tests and fixes Issue #169
=> Test fixes

admin/fleetcommander/fcdbus.py
Continuation of PR #195 
Rebased onto master.
=> Throw an useful error when no homedir is present

admin/cockpit/fleet-commander-admin/js/index.js
=> cockpit: Disabled click event in VMs that are running

admin/cockpit/fleet-commander-admin/js/index.js
=> cockpit: Added a message when VM list is empty. Fixes #199

admin/cockpit/fleet-commander-admin/js/livesession.js
It's easier to select/deselect all the changes of a section by
clicking on just one checkbox.
Fixes: https://github.com/fleet-commander/fc-admin/issues/218
=> Improve Profile Changes UI

admin/fleetcommander/sshcontroller.py
- catch root command prompt
- set $TERM env variable
- check if libvirt host already has our pubkey
=> Fix install pubkey into libvirt host

admin/cockpit/fleet-commander-admin/js/goa.js, admin/cockpit/fleet-commander-admin/js/index.js
The Return key pressing for performing some actions is the most
common approach to speed up some user interaction operations and
improve UX.
Particularly the corresponding events have been added to all
modal dialogs.
=> Add Return keypress events

admin/cockpit/fleet-commander-admin/js/index.js
Cleanup references to no longer existing ids.
=> Cleanup references to no longer existing ids

logger/fleet_commander_logger.py
=> Fix firefox profile directory detection

logger/fleet_commander_logger.py
`ScreenSaverInhibitor` has several bugs (flaws) due to which it may not send `Inhibit` to the screensaver (e. g. when the screensaver interrupts and resumes after a while) or may cause a crash (https://github.com/fleet-commander/fc-admin/issues/253)
This PR allows `ScreenSaverInhibitor` to monitor the DBus screensaver services (via `NameOwnerChanged` signals) and sends them `Inhibit` if they become active. `ScreenSaverInhibitor` remembers all active screensavers and sends `Uninhibit` to them on FC-logger shutdown process. If any of the active screensavers interrupts and resumes after a while, then `Inhibit` will be sent again.
Fixes: https://github.com/fleet-commander/fc-admin/issues/253
=> FC-logger: improve ScreenSaverInhibitor

admin/fleetcommander/libvirtcontroller.py
=> Fix snapshot option compatibility

tests/03_logger_firefox.py, tests/data/libvirt_domain-modified.xml
=> Fix tests according with last changes

logger/fleet_commander_logger.py
=> Fix crash firefox_bookmark when removing bookmarks

admin/cockpit/fleet-commander-admin/js/fcdbusclient.js, admin/cockpit/fleet-commander-admin/js/fcspiceclient.js, admin/cockpit/fleet-commander-admin/js/livesession.js, admin/cockpit/fleet-commander-admin/livesession.html, admin/cockpit/fleet-commander-admin/manifest.json
This PR is pending on an upstream patch to SPICE-html5 project:
https://lists.freedesktop.org/archives/spice-devel/2020-May/051681.html
When the patch reaches upstream we shoudl be able to update spice-html5 client submodule and rebase this.
=> SPICE: Updated spice client related code

tests/azure/azure-pipelines.yml
=> ci: Added distcheck to CI checks

Makefile.am, admin/fleetcommander/fcfreeipa.py, tests/_fcdbus_tests.py, tests/azure/azure-pipelines.yml
Fixes: https://github.com/fleet-commander/fc-admin/issues/268
=> pylint: Fix new warnings

tests/azure/templates/variables-fedora.yml
F32 will be EOL soon.
Fixes: https://github.com/fleet-commander/fc-admin/issues/273
=> azure: Switch to F34 Docker image
