- admin/fleetcommander/admin.py
- tests/04_admin.py
This adds a WSGI method to get "applies" objects, once we port all the client-side bits to use "/clientdata/" we can get rid of both ^/profiles$ and  ^/profiles/applies$
> admin: split applies-to into a different database/file

- .gitmodules
- admin/fleetcommander/collectors.py
- logger/fleet_commander_logger.js
- tests/03_logger_nm.js
This branch adds support for NetworkManager by logging settings and encoding them in a little endian base64 string inside the json payload. The configuration blob is also represented as json for convenience but that data is ignored by the client side.
To test this the wip/networkmanager branch of fc-client is needed.
> NetworkManager settings support for FleetCommander

- logger/fleet_commander_logger.js
- tests/_01_logger_test_suite.js
Switch to GVariant print() for greater reliability. Test with fc-client branch of the same name (wip/variantdata-gsettings)
> logger: store dconf data as a GVariant print() string

- data/Makefile.am
- data/org.freedesktop.FleetCommander.admin.metainfo.xml
This makes the Fleet Commander admin interface appear as an
installable application inside Cockpit.
> data: Add AppStream metainfo

- admin/fleetcommander/fcdbus.py
Missing mergers initialization were responsible of failing at profile saving. This PR fixes Issue #174
> fcdbus: Added missing mergers for Chromium/Chrome

- configure.ac
- package-requirements.txt
fc-admin no longer uses the gobject package. The last "import gobject"
was removed in commit 1710278761c8b80ee19c2cc357d287ebd49e7c55. Instead
of gobject, fc-admin has been using the 'gi' package.
Fedora doesn't have pygobject2 for Python 3. The python3-gobject package
provides gi bindings.
Signed-off-by: Christian Heimes <cheimes@redhat.com>
> [Py3] Remove dependency on gobject

- tests/00_database.py
- tests/00_freeipa.py
- tests/00_sshcontroller.py
- tests/01_logger_dconf.sh
- tests/01_mergers.py
- tests/02_logger_connmgr.py
- tests/03_logger_chromium.py
- tests/03_logger_firefox.py
- tests/03_logger_nm.py
- tests/04_libvirt_controller.py
- tests/05_fcdbus.sh
- tests/Makefile.am
- tests/_01_logger_test_suite.py
- tests/_01_mock_dbus.py
- tests/_01_wait_for_name.py
- tests/_05_fcdbus_tests.py
- tests/freeipamock.py
- tests/libvirtmock.py
- tests/python-wrapper.sh
- tests/test_fcdbus_service.py
The environment has been modified to use PYTHON variable to specify what interpreter to use:
PYTHON=python2 ./configure
or
PYTHON=python3 ./configure
> Prepared environment to be able to test Python 2 and 3 by changing it at config stage

- admin/fleetcommander/libvirtcontroller.py
This fixes the problems we had connecting to libvirt hosts using the Python3 version of FC
> libvirtcontroller: Fixed strings being passed as bytestrings. Fixes #208

- admin/cockpit/fleet-commander-admin/js/index.js
- admin/cockpit/fleet-commander-admin/js/livesession.js
Actually, log level is taken from FC config via DBus method
"GetInitialValues" having spec:
```
state = {
'debuglevel': self.log_level,
'defaults': {
'profilepriority': self.default_profile_priority,
}
}
```
So, actually, there is a typo debugLevel => debuglevel.
Fixes: https://github.com/fleet-commander/fc-admin/issues/214
> Fix logging to browser console

- admin/cockpit/fleet-commander-admin/livesession.html
As for now Google Chrome changes populate on not existing
HTML element (with the wrong id). It looks like a typo.
Fixes: https://github.com/fleet-commander/fc-admin/issues/220
> Fix Chrome changes populating

- data/org.freedesktop.FleetCommander.admin.metainfo.xml
* Add missing <?xml> header
* Update `<extends>` to renamed cockpit ID, as "cockpit.desktop" is
invalid (§ 2.1.3 [1]) and got changed in [2]
* Avoid whitespace in `<summary>`
* Add homepage URL
`appstream-util validate-relax data/org.freedesktop.FleetCommander.admin.metainfo.xml`
is happy now. `validate` only warns about a missing <update_contact>,
but this is optional.
[1] https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent
[2] https://github.com/cockpit-project/cockpit/pull/11557
> Fix cockpit plugin AppStream metadata

- admin/fleetcommander/fcdbus.py
As for now the name of new (renamed) profile in a log is the same as an old one:
```
FC: [DEBUG] Profile is being renamed from test to test
FC: [DEBUG] Saving profile into domain server
FC: [DEBUG] FreeIPAConnector: Profile needs renaming from test to test_
```
In fact, "name" keeps a new name of the profile.
> Fix logging value of renamed profile name

- admin/fleetcommander/fcdbus.py
As for now if the realmd package is not installed then an error
happens. But the reason for this error is not obvious.
Fixes: https://github.com/fleet-commander/fc-admin/issues/224
> Add explicit error message for realmd

- admin/cockpit/fleet-commander-admin/js/index.js
At the moment currentuid is populated with some value only on
edit an existing profile. The same should be made on creating a
new one. For now, this value is applied for storing a profile in AD.
> Fill up currentuid on adding a new profile

- admin/Makefile.am
- admin/cockpit/fleet-commander-admin/index.html
- admin/cockpit/fleet-commander-admin/js/base.js
- admin/cockpit/fleet-commander-admin/js/dialogs.js
- admin/cockpit/fleet-commander-admin/js/fcspiceclient.js
- admin/cockpit/fleet-commander-admin/js/goa.js
- admin/cockpit/fleet-commander-admin/js/highlightedapps.js
- admin/cockpit/fleet-commander-admin/js/index.js
- admin/cockpit/fleet-commander-admin/js/livesession.js
- admin/cockpit/fleet-commander-admin/livesession.html
As for now, there are several basic methods for operating common
dialogs. These methods include only the display of such messages.
For the other actions, the caller of dialog has to do it in his
own way. For example, there is no central point for closing or
event handling.
This patch adds base dialog class and several derived. Now we can
easily manage spinner, question and message dialogs in one place.
Fixes: https://github.com/fleet-commander/fc-admin/issues/222
> Add Dialog classes

- admin/fleetcommander/fcdbus.py
As for now, the specification of SSH port for connections is
ambiguous in FC as one part of code requires 'host port', while
another 'host:port'. From now on, the only supported by FC
specification of SSH port for connections is 'host:port'.
Fixes: https://github.com/fleet-commander/fc-admin/issues/243
> Correctly parse SSH host:port specification

- tests/04_libvirt_controller.py
- tests/libvirtmock.py
https://docs.python.org/3/library/xml.etree.elementtree.html
> Prior to Python 3.8, the serialisation order of the XML attributes of
elements was artificially made predictable by sorting the attributes by
their name. Based on the now guaranteed ordering of dicts, this
arbitrary reordering was removed in Python 3.8 to preserve the order in
which attributes were originally parsed or created by user code.
As of Python3.8:
> Canonicalization is a way to normalise XML output in a way that allows
byte-by-byte comparisons and digital signatures. It reduced the freedom
that XML serializers have and instead generates a more constrained XML
representation. The main restrictions regard the placement of namespace
declarations, the ordering of attributes, and ignorable whitespace.
In order to support …
> tests: Make use of sorting of XML attributes

- Makefile.am
- pylintrc
- tests/azure/azure-pipelines.yml
- tools/chrome-prefs-extract.py
Fix lint against new Pylint 2.8
- replace open with contextmanager where reasonable
- globally ignore `consider-using-with`, `consider-using-min-builtin`
and `consider-using-max-builtin`
Fixes: https://github.com/fleet-commander/fc-admin/issues/271
> Fix lint against new Pylint 2.8

- admin/fleetcommander/fcad.py
- tests/smbmock.py
Removed the sign parameter from the libsmb.Conn object initialization.
> Fixed invalid signature for libsmb.Conn object. Fixes #275

- admin/fleetcommander/fcfreeipa.py
- admin/fleetcommander/goa.py
- admin/fleetcommander/sshcontroller.py
- admin/fleetcommander/utils.py
- configure.ac
- data/fleet-commander-logger.in
- fleet-commander-admin.spec
- logger/fleet_commander_logger.py
- tests/Makefile.am
- tests/_logger_nm.py
- tests/_wait_for_name.py
- tests/freeipamock.py
- tests/python-wrapper.sh
- tests/test_freeipa.py
- tests/test_sshcontroller.py
Removed all components that supported python2 from tests and enforced python3 dependency on autotools.
> Python 2 deprecation

- admin/fleetcommander/database.py
- admin/fleetcommander/fcad.py
- admin/fleetcommander/fcdbus.py
- admin/fleetcommander/fcfreeipa.py
- admin/fleetcommander/sshcontroller.py
- logger/fleet_commander_logger.py
- pylintrc
- tests/_fcdbus_tests.py
- tests/_logger_test_suite.py
- tests/azure/templates/prepare-lint-fedora.yml
- tests/directorymock.py
- tests/freeipamock.py
- tests/smbmock.py
- tests/test_fcdbus_service.py
- tests/test_libvirt_controller.py
- tests/test_logger_chromium.py
- tests/test_logger_connmgr.py
- tests/test_logger_firefox.py
- tests/test_sshcontroller.py
- tools/chrome-prefs-extract.py
fixes for Pylint issues such as:
- `consider-using-f-string`
- `consider-iterating-dictionary`
- `unspecified-encoding`
- `use-implicit-booleaness-not-comparison`
- `use-list-literal`
- `consider-using-dict-items`
Fixes: https://github.com/fleet-commander/fc-admin/issues/279
> Pylint 2.12 fixes

- Makefile.am
- admin/cockpit/fleet-commander-admin/js/livesession.js
- admin/cockpit/fleet-commander-admin/livesession.html
- logger/fleet_commander_logger.py
Bug description:
If fc-logger is not installed on VM template then the behaviour of
fc-admin may confuse users.
During VM session a user makes some changes, see Review and submit
button available/enabled and after clicking on that button wonders that
there are no changes actually made.
This is typical error of setup.
Fix description:
Disable Review button by default and wait for IO with notifier
(initial message of notifier protocol) to enable it. Also
added helpful button tooltip.
Fixes: https://github.com/fleet-commander/fc-admin/issues/282
> admin: Enable Review button conditionally
